//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appProveedores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Facturas
    {
        public int idFactura { get; set; }
        public System.Guid idPago { get; set; }
        [Display(Name = "Razón Social")]
        [DataType(DataType.Text)]
        public string razonSocial { get; set; }
        [Display(Name = "RFC")]
        [DataType(DataType.Text)]
        public string RFC { get; set; }
        public string fechaFacturacion { get; set; }
    
        public virtual Pago Pago { get; set; }
    }
}
