//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appProveedores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int idPago { get; set; }
        public int idTarjeta { get; set; }
        public int idPedido { get; set; }
        public float montoPago { get; set; }
        public System.DateTime fechaPago { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
    }
}
