//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appProveedores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class ProductoPedido
    {
        public int id { get; set; }
        public int idProducto { get; set; }
        public int idPedido { get; set; }
        [Display(Name = "Cantidad")]
        public int cantidad { get; set; }
        public Nullable<float> descuento { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
